package entity;

import java.util.Date;

public class QuestionnaireMsg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_msg.msg_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String msgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_msg.msg_text
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String msgText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_msg.main_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String mainId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_msg.msg_creatuser
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String msgCreatuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_msg.msg_creattime
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private Date msgCreattime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_msg.msg_id
	 * @return  the value of questionnaire_msg.msg_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getMsgId() {
		return msgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_msg.msg_id
	 * @param msgId  the value for questionnaire_msg.msg_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMsgId(String msgId) {
		this.msgId = msgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_msg.msg_text
	 * @return  the value of questionnaire_msg.msg_text
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getMsgText() {
		return msgText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_msg.msg_text
	 * @param msgText  the value for questionnaire_msg.msg_text
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMsgText(String msgText) {
		this.msgText = msgText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_msg.main_id
	 * @return  the value of questionnaire_msg.main_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getMainId() {
		return mainId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_msg.main_id
	 * @param mainId  the value for questionnaire_msg.main_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMainId(String mainId) {
		this.mainId = mainId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_msg.msg_creatuser
	 * @return  the value of questionnaire_msg.msg_creatuser
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getMsgCreatuser() {
		return msgCreatuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_msg.msg_creatuser
	 * @param msgCreatuser  the value for questionnaire_msg.msg_creatuser
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMsgCreatuser(String msgCreatuser) {
		this.msgCreatuser = msgCreatuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_msg.msg_creattime
	 * @return  the value of questionnaire_msg.msg_creattime
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public Date getMsgCreattime() {
		return msgCreattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_msg.msg_creattime
	 * @param msgCreattime  the value for questionnaire_msg.msg_creattime
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMsgCreattime(Date msgCreattime) {
		this.msgCreattime = msgCreattime;
	}
}