package entity;

public class QuestionnaireMainUserKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_main_user.user_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_main_user.main_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String mainId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_main_user.user_id
	 * @return  the value of questionnaire_main_user.user_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_main_user.user_id
	 * @param userId  the value for questionnaire_main_user.user_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_main_user.main_id
	 * @return  the value of questionnaire_main_user.main_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getMainId() {
		return mainId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_main_user.main_id
	 * @param mainId  the value for questionnaire_main_user.main_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMainId(String mainId) {
		this.mainId = mainId;
	}
}