package entity;

import java.util.Date;

public class QuestionnaireMain {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_main.main_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String mainId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_main.main_title
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String mainTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_main.main_creat
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private Date mainCreat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_main.main_isuse
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String mainIsuse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_main.main_endtime
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private Date mainEndtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_main.main_creatuser
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String mainCreatuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questionnaire_main.main_creatdep
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private Integer mainCreatdep;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_main.main_id
	 * @return  the value of questionnaire_main.main_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getMainId() {
		return mainId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_main.main_id
	 * @param mainId  the value for questionnaire_main.main_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMainId(String mainId) {
		this.mainId = mainId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_main.main_title
	 * @return  the value of questionnaire_main.main_title
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getMainTitle() {
		return mainTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_main.main_title
	 * @param mainTitle  the value for questionnaire_main.main_title
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMainTitle(String mainTitle) {
		this.mainTitle = mainTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_main.main_creat
	 * @return  the value of questionnaire_main.main_creat
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public Date getMainCreat() {
		return mainCreat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_main.main_creat
	 * @param mainCreat  the value for questionnaire_main.main_creat
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMainCreat(Date mainCreat) {
		this.mainCreat = mainCreat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_main.main_isuse
	 * @return  the value of questionnaire_main.main_isuse
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getMainIsuse() {
		return mainIsuse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_main.main_isuse
	 * @param mainIsuse  the value for questionnaire_main.main_isuse
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMainIsuse(String mainIsuse) {
		this.mainIsuse = mainIsuse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_main.main_endtime
	 * @return  the value of questionnaire_main.main_endtime
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public Date getMainEndtime() {
		return mainEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_main.main_endtime
	 * @param mainEndtime  the value for questionnaire_main.main_endtime
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMainEndtime(Date mainEndtime) {
		this.mainEndtime = mainEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_main.main_creatuser
	 * @return  the value of questionnaire_main.main_creatuser
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getMainCreatuser() {
		return mainCreatuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_main.main_creatuser
	 * @param mainCreatuser  the value for questionnaire_main.main_creatuser
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMainCreatuser(String mainCreatuser) {
		this.mainCreatuser = mainCreatuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questionnaire_main.main_creatdep
	 * @return  the value of questionnaire_main.main_creatdep
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public Integer getMainCreatdep() {
		return mainCreatdep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questionnaire_main.main_creatdep
	 * @param mainCreatdep  the value for questionnaire_main.main_creatdep
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setMainCreatdep(Integer mainCreatdep) {
		this.mainCreatdep = mainCreatdep;
	}
}