package entity;

public class SysLoginRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_login_role.id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_login_role.login_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private Integer loginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_login_role.role_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_login_role.username
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String username;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_login_role.id
	 * @return  the value of sys_login_role.id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_login_role.id
	 * @param id  the value for sys_login_role.id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_login_role.login_id
	 * @return  the value of sys_login_role.login_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public Integer getLoginId() {
		return loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_login_role.login_id
	 * @param loginId  the value for sys_login_role.login_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setLoginId(Integer loginId) {
		this.loginId = loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_login_role.role_id
	 * @return  the value of sys_login_role.role_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_login_role.role_id
	 * @param roleId  the value for sys_login_role.role_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_login_role.username
	 * @return  the value of sys_login_role.username
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_login_role.username
	 * @param username  the value for sys_login_role.username
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}
}