package entity;

import java.util.Date;

public class WorkDay {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column work_day.work_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String workId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column work_day.work_title
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String workTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column work_day.work_start
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private Date workStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column work_day.work_end
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private Date workEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column work_day.work_color
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String workColor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column work_day.work_scope
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	private String workScope;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column work_day.work_id
	 * @return  the value of work_day.work_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getWorkId() {
		return workId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column work_day.work_id
	 * @param workId  the value for work_day.work_id
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setWorkId(String workId) {
		this.workId = workId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column work_day.work_title
	 * @return  the value of work_day.work_title
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getWorkTitle() {
		return workTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column work_day.work_title
	 * @param workTitle  the value for work_day.work_title
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setWorkTitle(String workTitle) {
		this.workTitle = workTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column work_day.work_start
	 * @return  the value of work_day.work_start
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public Date getWorkStart() {
		return workStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column work_day.work_start
	 * @param workStart  the value for work_day.work_start
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setWorkStart(Date workStart) {
		this.workStart = workStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column work_day.work_end
	 * @return  the value of work_day.work_end
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public Date getWorkEnd() {
		return workEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column work_day.work_end
	 * @param workEnd  the value for work_day.work_end
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setWorkEnd(Date workEnd) {
		this.workEnd = workEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column work_day.work_color
	 * @return  the value of work_day.work_color
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getWorkColor() {
		return workColor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column work_day.work_color
	 * @param workColor  the value for work_day.work_color
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setWorkColor(String workColor) {
		this.workColor = workColor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column work_day.work_scope
	 * @return  the value of work_day.work_scope
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public String getWorkScope() {
		return workScope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column work_day.work_scope
	 * @param workScope  the value for work_day.work_scope
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	public void setWorkScope(String workScope) {
		this.workScope = workScope;
	}
}