package dao;

import entity.QuestionnaireMsg;

public interface QuestionnaireMsgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_msg
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int deleteByPrimaryKey(String msgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_msg
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int insert(QuestionnaireMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_msg
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int insertSelective(QuestionnaireMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_msg
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	QuestionnaireMsg selectByPrimaryKey(String msgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_msg
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int updateByPrimaryKeySelective(QuestionnaireMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_msg
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int updateByPrimaryKey(QuestionnaireMsg record);
}