package dao;

import entity.QuestionnaireQuestion;

public interface QuestionnaireQuestionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_question
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int deleteByPrimaryKey(String questionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_question
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int insert(QuestionnaireQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_question
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int insertSelective(QuestionnaireQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_question
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	QuestionnaireQuestion selectByPrimaryKey(String questionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_question
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int updateByPrimaryKeySelective(QuestionnaireQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_question
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int updateByPrimaryKey(QuestionnaireQuestion record);
}