package dao;

import entity.QuestionnaireMain;

public interface QuestionnaireMainMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_main
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int deleteByPrimaryKey(String mainId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_main
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int insert(QuestionnaireMain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_main
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int insertSelective(QuestionnaireMain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_main
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	QuestionnaireMain selectByPrimaryKey(String mainId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_main
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int updateByPrimaryKeySelective(QuestionnaireMain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questionnaire_main
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int updateByPrimaryKey(QuestionnaireMain record);
}