package dao;

import entity.SysPermission;

public interface SysPermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int deleteByPrimaryKey(Integer permissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int insert(SysPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int insertSelective(SysPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	SysPermission selectByPrimaryKey(Integer permissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int updateByPrimaryKeySelective(SysPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int updateByPrimaryKey(SysPermission record);
}