package dao;

import entity.SysRole;

public interface SysRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int deleteByPrimaryKey(Integer roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int insert(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int insertSelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	SysRole selectByPrimaryKey(Integer roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int updateByPrimaryKeySelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int updateByPrimaryKey(SysRole record);
}