package dao;

import entity.SysRolePermission;

public interface SysRolePermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_permission
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_permission
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int insert(SysRolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_permission
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int insertSelective(SysRolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_permission
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	SysRolePermission selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_permission
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int updateByPrimaryKeySelective(SysRolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_permission
	 * @mbg.generated  Thu Nov 01 10:56:55 CST 2018
	 */
	int updateByPrimaryKey(SysRolePermission record);
}