package sqlmapping;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuestionnaireAnswerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public QuestionnaireAnswerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAnswerIdIsNull() {
            addCriterion("answer_id is null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIsNotNull() {
            addCriterion("answer_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdEqualTo(String value) {
            addCriterion("answer_id =", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotEqualTo(String value) {
            addCriterion("answer_id <>", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThan(String value) {
            addCriterion("answer_id >", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThanOrEqualTo(String value) {
            addCriterion("answer_id >=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThan(String value) {
            addCriterion("answer_id <", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThanOrEqualTo(String value) {
            addCriterion("answer_id <=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLike(String value) {
            addCriterion("answer_id like", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotLike(String value) {
            addCriterion("answer_id not like", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIn(List<String> values) {
            addCriterion("answer_id in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotIn(List<String> values) {
            addCriterion("answer_id not in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdBetween(String value1, String value2) {
            addCriterion("answer_id between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotBetween(String value1, String value2) {
            addCriterion("answer_id not between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerValueIsNull() {
            addCriterion("answer_value is null");
            return (Criteria) this;
        }

        public Criteria andAnswerValueIsNotNull() {
            addCriterion("answer_value is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerValueEqualTo(Integer value) {
            addCriterion("answer_value =", value, "answerValue");
            return (Criteria) this;
        }

        public Criteria andAnswerValueNotEqualTo(Integer value) {
            addCriterion("answer_value <>", value, "answerValue");
            return (Criteria) this;
        }

        public Criteria andAnswerValueGreaterThan(Integer value) {
            addCriterion("answer_value >", value, "answerValue");
            return (Criteria) this;
        }

        public Criteria andAnswerValueGreaterThanOrEqualTo(Integer value) {
            addCriterion("answer_value >=", value, "answerValue");
            return (Criteria) this;
        }

        public Criteria andAnswerValueLessThan(Integer value) {
            addCriterion("answer_value <", value, "answerValue");
            return (Criteria) this;
        }

        public Criteria andAnswerValueLessThanOrEqualTo(Integer value) {
            addCriterion("answer_value <=", value, "answerValue");
            return (Criteria) this;
        }

        public Criteria andAnswerValueIn(List<Integer> values) {
            addCriterion("answer_value in", values, "answerValue");
            return (Criteria) this;
        }

        public Criteria andAnswerValueNotIn(List<Integer> values) {
            addCriterion("answer_value not in", values, "answerValue");
            return (Criteria) this;
        }

        public Criteria andAnswerValueBetween(Integer value1, Integer value2) {
            addCriterion("answer_value between", value1, value2, "answerValue");
            return (Criteria) this;
        }

        public Criteria andAnswerValueNotBetween(Integer value1, Integer value2) {
            addCriterion("answer_value not between", value1, value2, "answerValue");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeIsNull() {
            addCriterion("answer_type is null");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeIsNotNull() {
            addCriterion("answer_type is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeEqualTo(String value) {
            addCriterion("answer_type =", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeNotEqualTo(String value) {
            addCriterion("answer_type <>", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeGreaterThan(String value) {
            addCriterion("answer_type >", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeGreaterThanOrEqualTo(String value) {
            addCriterion("answer_type >=", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeLessThan(String value) {
            addCriterion("answer_type <", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeLessThanOrEqualTo(String value) {
            addCriterion("answer_type <=", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeLike(String value) {
            addCriterion("answer_type like", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeNotLike(String value) {
            addCriterion("answer_type not like", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeIn(List<String> values) {
            addCriterion("answer_type in", values, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeNotIn(List<String> values) {
            addCriterion("answer_type not in", values, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeBetween(String value1, String value2) {
            addCriterion("answer_type between", value1, value2, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeNotBetween(String value1, String value2) {
            addCriterion("answer_type not between", value1, value2, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeIsNull() {
            addCriterion("answer_destype is null");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeIsNotNull() {
            addCriterion("answer_destype is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeEqualTo(String value) {
            addCriterion("answer_destype =", value, "answerDestype");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeNotEqualTo(String value) {
            addCriterion("answer_destype <>", value, "answerDestype");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeGreaterThan(String value) {
            addCriterion("answer_destype >", value, "answerDestype");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeGreaterThanOrEqualTo(String value) {
            addCriterion("answer_destype >=", value, "answerDestype");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeLessThan(String value) {
            addCriterion("answer_destype <", value, "answerDestype");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeLessThanOrEqualTo(String value) {
            addCriterion("answer_destype <=", value, "answerDestype");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeLike(String value) {
            addCriterion("answer_destype like", value, "answerDestype");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeNotLike(String value) {
            addCriterion("answer_destype not like", value, "answerDestype");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeIn(List<String> values) {
            addCriterion("answer_destype in", values, "answerDestype");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeNotIn(List<String> values) {
            addCriterion("answer_destype not in", values, "answerDestype");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeBetween(String value1, String value2) {
            addCriterion("answer_destype between", value1, value2, "answerDestype");
            return (Criteria) this;
        }

        public Criteria andAnswerDestypeNotBetween(String value1, String value2) {
            addCriterion("answer_destype not between", value1, value2, "answerDestype");
            return (Criteria) this;
        }

        public Criteria andAnswerTextIsNull() {
            addCriterion("answer_text is null");
            return (Criteria) this;
        }

        public Criteria andAnswerTextIsNotNull() {
            addCriterion("answer_text is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerTextEqualTo(String value) {
            addCriterion("answer_text =", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextNotEqualTo(String value) {
            addCriterion("answer_text <>", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextGreaterThan(String value) {
            addCriterion("answer_text >", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextGreaterThanOrEqualTo(String value) {
            addCriterion("answer_text >=", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextLessThan(String value) {
            addCriterion("answer_text <", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextLessThanOrEqualTo(String value) {
            addCriterion("answer_text <=", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextLike(String value) {
            addCriterion("answer_text like", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextNotLike(String value) {
            addCriterion("answer_text not like", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextIn(List<String> values) {
            addCriterion("answer_text in", values, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextNotIn(List<String> values) {
            addCriterion("answer_text not in", values, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextBetween(String value1, String value2) {
            addCriterion("answer_text between", value1, value2, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextNotBetween(String value1, String value2) {
            addCriterion("answer_text not between", value1, value2, "answerText");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNull() {
            addCriterion("question_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNotNull() {
            addCriterion("question_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdEqualTo(String value) {
            addCriterion("question_id =", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotEqualTo(String value) {
            addCriterion("question_id <>", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThan(String value) {
            addCriterion("question_id >", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThanOrEqualTo(String value) {
            addCriterion("question_id >=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThan(String value) {
            addCriterion("question_id <", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThanOrEqualTo(String value) {
            addCriterion("question_id <=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLike(String value) {
            addCriterion("question_id like", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotLike(String value) {
            addCriterion("question_id not like", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIn(List<String> values) {
            addCriterion("question_id in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotIn(List<String> values) {
            addCriterion("question_id not in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdBetween(String value1, String value2) {
            addCriterion("question_id between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotBetween(String value1, String value2) {
            addCriterion("question_id not between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andAnswerCreatIsNull() {
            addCriterion("answer_creat is null");
            return (Criteria) this;
        }

        public Criteria andAnswerCreatIsNotNull() {
            addCriterion("answer_creat is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerCreatEqualTo(Date value) {
            addCriterion("answer_creat =", value, "answerCreat");
            return (Criteria) this;
        }

        public Criteria andAnswerCreatNotEqualTo(Date value) {
            addCriterion("answer_creat <>", value, "answerCreat");
            return (Criteria) this;
        }

        public Criteria andAnswerCreatGreaterThan(Date value) {
            addCriterion("answer_creat >", value, "answerCreat");
            return (Criteria) this;
        }

        public Criteria andAnswerCreatGreaterThanOrEqualTo(Date value) {
            addCriterion("answer_creat >=", value, "answerCreat");
            return (Criteria) this;
        }

        public Criteria andAnswerCreatLessThan(Date value) {
            addCriterion("answer_creat <", value, "answerCreat");
            return (Criteria) this;
        }

        public Criteria andAnswerCreatLessThanOrEqualTo(Date value) {
            addCriterion("answer_creat <=", value, "answerCreat");
            return (Criteria) this;
        }

        public Criteria andAnswerCreatIn(List<Date> values) {
            addCriterion("answer_creat in", values, "answerCreat");
            return (Criteria) this;
        }

        public Criteria andAnswerCreatNotIn(List<Date> values) {
            addCriterion("answer_creat not in", values, "answerCreat");
            return (Criteria) this;
        }

        public Criteria andAnswerCreatBetween(Date value1, Date value2) {
            addCriterion("answer_creat between", value1, value2, "answerCreat");
            return (Criteria) this;
        }

        public Criteria andAnswerCreatNotBetween(Date value1, Date value2) {
            addCriterion("answer_creat not between", value1, value2, "answerCreat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table questionnaire_answer
     *
     * @mbg.generated do_not_delete_during_merge Wed Oct 31 16:51:29 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}