package sqlmapping;

import java.util.Date;

public class QuestionnaireQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_question.question_id
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_question.question_title
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String questionTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_question.question_creat
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private Date questionCreat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_question.question_destype
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String questionDestype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_question.question_type
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String questionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_question.main_id
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String mainId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_question.question_id
     *
     * @return the value of questionnaire_question.question_id
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_question.question_id
     *
     * @param questionId the value for questionnaire_question.question_id
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_question.question_title
     *
     * @return the value of questionnaire_question.question_title
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getQuestionTitle() {
        return questionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_question.question_title
     *
     * @param questionTitle the value for questionnaire_question.question_title
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setQuestionTitle(String questionTitle) {
        this.questionTitle = questionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_question.question_creat
     *
     * @return the value of questionnaire_question.question_creat
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public Date getQuestionCreat() {
        return questionCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_question.question_creat
     *
     * @param questionCreat the value for questionnaire_question.question_creat
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setQuestionCreat(Date questionCreat) {
        this.questionCreat = questionCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_question.question_destype
     *
     * @return the value of questionnaire_question.question_destype
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getQuestionDestype() {
        return questionDestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_question.question_destype
     *
     * @param questionDestype the value for questionnaire_question.question_destype
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setQuestionDestype(String questionDestype) {
        this.questionDestype = questionDestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_question.question_type
     *
     * @return the value of questionnaire_question.question_type
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_question.question_type
     *
     * @param questionType the value for questionnaire_question.question_type
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setQuestionType(String questionType) {
        this.questionType = questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_question.main_id
     *
     * @return the value of questionnaire_question.main_id
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getMainId() {
        return mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_question.main_id
     *
     * @param mainId the value for questionnaire_question.main_id
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setMainId(String mainId) {
        this.mainId = mainId;
    }
}