package sqlmapping;

import sqlmapping.QuestionnaireMainUserKey;

public interface QuestionnaireMainUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_main_user
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int deleteByPrimaryKey(QuestionnaireMainUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_main_user
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int insert(QuestionnaireMainUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_main_user
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int insertSelective(QuestionnaireMainUserKey record);
}