package sqlmapping;

import sqlmapping.QuestionnaireAnswer;

public interface QuestionnaireAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int deleteByPrimaryKey(String answerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int insert(QuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int insertSelective(QuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    QuestionnaireAnswer selectByPrimaryKey(String answerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int updateByPrimaryKeySelective(QuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int updateByPrimaryKey(QuestionnaireAnswer record);
}