package sqlmapping;

import java.util.Date;

public class QuestionnaireAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_answer.answer_id
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    private String answerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_answer.answer_value
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    private Integer answerValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_answer.answer_type
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    private String answerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_answer.answer_destype
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    private String answerDestype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_answer.answer_text
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    private String answerText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_answer.question_id
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    private String questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_answer.answer_creat
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    private Date answerCreat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_answer.answer_id
     *
     * @return the value of questionnaire_answer.answer_id
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public String getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_answer.answer_id
     *
     * @param answerId the value for questionnaire_answer.answer_id
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public void setAnswerId(String answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_answer.answer_value
     *
     * @return the value of questionnaire_answer.answer_value
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public Integer getAnswerValue() {
        return answerValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_answer.answer_value
     *
     * @param answerValue the value for questionnaire_answer.answer_value
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public void setAnswerValue(Integer answerValue) {
        this.answerValue = answerValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_answer.answer_type
     *
     * @return the value of questionnaire_answer.answer_type
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public String getAnswerType() {
        return answerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_answer.answer_type
     *
     * @param answerType the value for questionnaire_answer.answer_type
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public void setAnswerType(String answerType) {
        this.answerType = answerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_answer.answer_destype
     *
     * @return the value of questionnaire_answer.answer_destype
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public String getAnswerDestype() {
        return answerDestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_answer.answer_destype
     *
     * @param answerDestype the value for questionnaire_answer.answer_destype
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public void setAnswerDestype(String answerDestype) {
        this.answerDestype = answerDestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_answer.answer_text
     *
     * @return the value of questionnaire_answer.answer_text
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public String getAnswerText() {
        return answerText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_answer.answer_text
     *
     * @param answerText the value for questionnaire_answer.answer_text
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public void setAnswerText(String answerText) {
        this.answerText = answerText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_answer.question_id
     *
     * @return the value of questionnaire_answer.question_id
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_answer.question_id
     *
     * @param questionId the value for questionnaire_answer.question_id
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_answer.answer_creat
     *
     * @return the value of questionnaire_answer.answer_creat
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public Date getAnswerCreat() {
        return answerCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_answer.answer_creat
     *
     * @param answerCreat the value for questionnaire_answer.answer_creat
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    public void setAnswerCreat(Date answerCreat) {
        this.answerCreat = answerCreat;
    }
}