package sqlmapping;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sqlmapping.QuestionnaireAnswer;
import sqlmapping.QuestionnaireAnswerExample;

public interface QuestionnaireAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    long countByExample(QuestionnaireAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    int deleteByExample(QuestionnaireAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    int deleteByPrimaryKey(String answerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    int insert(QuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    int insertSelective(QuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    List<QuestionnaireAnswer> selectByExample(QuestionnaireAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    QuestionnaireAnswer selectByPrimaryKey(String answerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") QuestionnaireAnswer record, @Param("example") QuestionnaireAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    int updateByExample(@Param("record") QuestionnaireAnswer record, @Param("example") QuestionnaireAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    int updateByPrimaryKeySelective(QuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire_answer
     *
     * @mbg.generated Wed Oct 31 16:51:29 CST 2018
     */
    int updateByPrimaryKey(QuestionnaireAnswer record);
}