package sqlmapping;

public class SysLogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.login_id
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private Integer loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.username
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.password
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.email
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.wxname
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String wxname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.login_id
     *
     * @return the value of sys_login.login_id
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.login_id
     *
     * @param loginId the value for sys_login.login_id
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.username
     *
     * @return the value of sys_login.username
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.username
     *
     * @param username the value for sys_login.username
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.password
     *
     * @return the value of sys_login.password
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.password
     *
     * @param password the value for sys_login.password
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.email
     *
     * @return the value of sys_login.email
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.email
     *
     * @param email the value for sys_login.email
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.wxname
     *
     * @return the value of sys_login.wxname
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getWxname() {
        return wxname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.wxname
     *
     * @param wxname the value for sys_login.wxname
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setWxname(String wxname) {
        this.wxname = wxname;
    }
}