package sqlmapping;

import sqlmapping.SysLoginRole;

public interface SysLoginRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_role
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_role
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int insert(SysLoginRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_role
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int insertSelective(SysLoginRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_role
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    SysLoginRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_role
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int updateByPrimaryKeySelective(SysLoginRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_role
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int updateByPrimaryKey(SysLoginRole record);
}