package sqlmapping;

import sqlmapping.SysLogin;

public interface SysLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int deleteByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int insert(SysLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int insertSelective(SysLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    SysLogin selectByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int updateByPrimaryKeySelective(SysLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    int updateByPrimaryKey(SysLogin record);
}