package sqlmapping;

public class SysUserinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.sys_userid
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String sysUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.sys_username
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String sysUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.sys_sex
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String sysSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.sys_age
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private Integer sysAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.sys_language
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String sysLanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.sys_profession
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String sysProfession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.sys_name
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String sysName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.sys_userid
     *
     * @return the value of sys_userinfo.sys_userid
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getSysUserid() {
        return sysUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.sys_userid
     *
     * @param sysUserid the value for sys_userinfo.sys_userid
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setSysUserid(String sysUserid) {
        this.sysUserid = sysUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.sys_username
     *
     * @return the value of sys_userinfo.sys_username
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getSysUsername() {
        return sysUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.sys_username
     *
     * @param sysUsername the value for sys_userinfo.sys_username
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setSysUsername(String sysUsername) {
        this.sysUsername = sysUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.sys_sex
     *
     * @return the value of sys_userinfo.sys_sex
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getSysSex() {
        return sysSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.sys_sex
     *
     * @param sysSex the value for sys_userinfo.sys_sex
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setSysSex(String sysSex) {
        this.sysSex = sysSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.sys_age
     *
     * @return the value of sys_userinfo.sys_age
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public Integer getSysAge() {
        return sysAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.sys_age
     *
     * @param sysAge the value for sys_userinfo.sys_age
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setSysAge(Integer sysAge) {
        this.sysAge = sysAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.sys_language
     *
     * @return the value of sys_userinfo.sys_language
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getSysLanguage() {
        return sysLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.sys_language
     *
     * @param sysLanguage the value for sys_userinfo.sys_language
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setSysLanguage(String sysLanguage) {
        this.sysLanguage = sysLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.sys_profession
     *
     * @return the value of sys_userinfo.sys_profession
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getSysProfession() {
        return sysProfession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.sys_profession
     *
     * @param sysProfession the value for sys_userinfo.sys_profession
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setSysProfession(String sysProfession) {
        this.sysProfession = sysProfession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.sys_name
     *
     * @return the value of sys_userinfo.sys_name
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.sys_name
     *
     * @param sysName the value for sys_userinfo.sys_name
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setSysName(String sysName) {
        this.sysName = sysName;
    }
}