package sqlmapping;

import java.util.Date;

public class UserLogin extends UserLoginKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.password
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.role
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.infoname
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String infoname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.age
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.sex
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.tell
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String tell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.sfzh
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String sfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.address
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.creat_date
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private Date creatDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.update_date
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.password
     *
     * @return the value of user_login.password
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.password
     *
     * @param password the value for user_login.password
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.role
     *
     * @return the value of user_login.role
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.role
     *
     * @param role the value for user_login.role
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.infoname
     *
     * @return the value of user_login.infoname
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getInfoname() {
        return infoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.infoname
     *
     * @param infoname the value for user_login.infoname
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setInfoname(String infoname) {
        this.infoname = infoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.age
     *
     * @return the value of user_login.age
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.age
     *
     * @param age the value for user_login.age
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.sex
     *
     * @return the value of user_login.sex
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.sex
     *
     * @param sex the value for user_login.sex
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.tell
     *
     * @return the value of user_login.tell
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getTell() {
        return tell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.tell
     *
     * @param tell the value for user_login.tell
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setTell(String tell) {
        this.tell = tell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.sfzh
     *
     * @return the value of user_login.sfzh
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.sfzh
     *
     * @param sfzh the value for user_login.sfzh
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.address
     *
     * @return the value of user_login.address
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.address
     *
     * @param address the value for user_login.address
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.creat_date
     *
     * @return the value of user_login.creat_date
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public Date getCreatDate() {
        return creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.creat_date
     *
     * @param creatDate the value for user_login.creat_date
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setCreatDate(Date creatDate) {
        this.creatDate = creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.update_date
     *
     * @return the value of user_login.update_date
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.update_date
     *
     * @param updateDate the value for user_login.update_date
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}