package sqlmapping;

public class UserLoginKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.id
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.username
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.id
     *
     * @return the value of user_login.id
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.id
     *
     * @param id the value for user_login.id
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.username
     *
     * @return the value of user_login.username
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.username
     *
     * @param username the value for user_login.username
     *
     * @mbg.generated Thu Nov 01 10:34:09 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }
}